apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celery.deployment_name }}
  labels:
    app: {{ .Values.celery.pod_name }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.celery.pod_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.celery.pod_name }}
    spec:
      containers:
      - name: {{ .Values.celery.container_name }}
        image: {{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        command: {{ .Values.celery.image.command }}
        args: {{ .Values.celery.image.args }}
        env:
        - name: POSTGRESQLUSERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: username
        - name: POSTGRESQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: password
        - name: POSTGRESQLHOST
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: host
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: redis_url