apiVersion: v1
kind: Service
metadata:
  name: {{.Values.web.service_name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.web.pod_name }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort:  30000