apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.deployment_name }}
  labels:
    app: {{ .Values.web.pod_name }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.pod_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.pod_name }}
    spec:
      containers:
      - name: {{ .Values.web.container_name }}
        image: {{ .Values.web.image }}
        command: ["/bin/bash", "-c"]
        args: ["daphne -p 8080 idea_collector.asgi:application"]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQLUSERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRESQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRESQLHOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: host