apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.deployment_name }}
  labels:
    app: {{ .Values.web.pod_name }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.pod_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.pod_name }}
    spec:
      containers:
      - name: {{ .Values.web.container_name }}
        image: {{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        command: {{ .Values.web.image.command }}
        args: {{ .Values.web.image.args }}
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQLUSERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: username
        - name: POSTGRESQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: password
        - name: POSTGRESQLHOST
           secretKeyRef:
              name: postgres-redis-credentials
              key: host