apiVersion: v1
kind: Secret
metadata:
  name: postgres-redis-credentials
type: Opaque
stringData:
  username: {{ .Values.postgresql.postgresqlUsername }} 
  password: {{ .Values.postgresql.postgresqlPassword }}
  host: {{ .Values.postgres.fullnameOverride }}
  redis_url: {{ .Values.redis.fullnameOverride }}-master