apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  user: {{ .Values.postgresql.postgresqlUsername }} 
  password: {{ .Values.postgresql.postgresqlPassword }}
  host: {{ .Values.postgresql.postgresqlHost }}