# Generated by Django 3.0.8 on 2020-10-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20201012_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='body',
            new_name='description',
        ),
    ]
