# Generated by Django 3.1.3 on 2020-11-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20201104_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idea',
            new_name='IdeaModel',
        ),
    ]
