image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
    
services: 
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS

build-job:
  stage: build
  script:
    - docker build .
    - docker tag python:3.6 maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA
    - docker push maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA
 
test-job:
  stage: test
  script:
    - mv idea_collector/test_settings.py idea_collector/settings.py
    - docker run -it maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA
    - pipenv run python manage.py test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."