image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
    
services: 
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS
  - apk add --update py-pip
  - apk add libffi-dev openssl-dev gcc libc-dev make
  - apk add python-dev
  - pip install docker-compose

build-job:
  stage: build
  script:
    - docker build .
    - docker tag python:3.6 maorc112/idea_collector_web:latest
    - docker push maorc112/idea_collector_web:latest
 
test-job:
  stage: test
  script:
    - docker-compose up

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."