image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  SQLUSER: postgres
  PASSWORD: postgres
  HOST: db
    
services: 
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS

build-job:
  stage: build
  script:
    - docker build -t maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA .
    - docker push maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA
 
test-job:
  stage: test
  script:
    - mv idea_collector/test_settings.py idea_collector/settings.py
    - docker run maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA python manage.py test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."