image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

build-job:
  stage: build
  script:
    - docker build .
    - docker tag python:3.6 maorc112/idea_collector_web:latest
    - docker push maorc112/idea_collector_web:latest

    
test-job:
  stage: test
  script:
    - docker-compose up -d
    - docker exec -it idea_collector_web_1 bash
    - pipenv run python manage.py test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."