image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
    
services: 
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS

build-job:
  stage: build
  script:
    - docker build -t maorc112/idea_collector_web:latest .
    - docker push maorc112/idea_collector_web:latest

test-job:
  stage: test
  script:
    - docker run maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA /bin/bash -c "mv /code/idea_collector/test_settings.py /code/idea_collector/settings.py && pipenv run python manage.py makemigrations && pipenv run python manage.py migrate && pipenv run python manage.py test"

deploy-prod:
  stage: deploy
  script:
    - echo helm upgrade idea-collector ideaCollector --set postgresql.postgresqlUsername=POSTGRESUSERNAME --set postgresql.postgresqlPassword=POSTGRESPASSWORD --set postgresql.fullnameOverride=POSTGRESHOST --set web.image.tag=TAG --set redis.fullnameOverride=REDISNAME