image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
    
services: 
  - docker:dind

before_script:
  - docker login -u=$USERN -p=$PASS

build-job:
  stage: build
  script:
    - docker build -t maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA .
    - docker push maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA

test-job:
  stage: test
  script:
    - docker run maorc112/idea_collector_web:$CI_COMMIT_SHORT_SHA /bin/bash -c "mv /code/idea_collector/test_settings.py /code/idea_collector/settings.py && python manage.py test"

deploy-prod:
  stage: deploy
  script:
    - echo helm update idea-collector ideaCollector --set postgresqlUsername=POSTGRESQLUSERNAME --set postgresqlPassword=POSTGRESQLPASSWORD --set postgresqlHost=POSTGRESQLHOST