apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-collector-{{ name }}
  labels:
    app: idea-collector-{{ name }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: idea-collector-{{ name }}
  template:
    metadata:
      labels:
        app: idea-collector-{{ name }}
    spec:
      containers:
      - name: idea-collector-{{ name }}
        image: maorc112/idea_collector_web:latest
        command: 
        args: {{ command|safe }}
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQLUSERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: username
        - name: POSTGRESQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: password
        - name: POSTGRESQLHOST
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: host
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: postgres-redis-credentials
              key: redis_url