apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: idea-collectors.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: IdeaCollector
    singular: idea-collector
    plural: idea-collectors
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              web_app_replicas:
                type: integer
              celery_worker_replicas:
                type: integer
              postgres_name:
                type: string
              postgres_username:
                type: string
              postgres_password:
                type: string
              redis_name:
                type: string
              